[template]
cargo_generate_version = ">=0.10.0"

[placeholders]
project-title = { type = "string", prompt = "Project title?" }
project-description = { type = "string", prompt = "Project description?" }